# Generated by Django 6.0.5 on 2026-05-13 01:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('img_pc', models.TextField(db_column='imgPc')),
                ('img_mobile', models.TextField(db_column='imgMobile')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='reatedAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Banner',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'BlogCategory',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'Brand',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('icon', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('hex', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Color',
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Condition',
            },
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'Info',
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'Memory',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
            ],
            options={
                'db_table': 'ProductModel',
            },
        ),
        migrations.CreateModel(
            name='ServiceBrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('image', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'ServiceBrand',
            },
        ),
        migrations.CreateModel(
            name='SimType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'SimType',
            },
        ),
        migrations.CreateModel(
            name='StoreAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.TextField(unique=True)),
                ('password', models.TextField()),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='StoreUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.TextField(blank=True, db_column='firstName', null=True)),
                ('last_name', models.TextField(blank=True, db_column='lastName', null=True)),
                ('middle_name', models.TextField(blank=True, db_column='middleName', null=True)),
                ('email', models.TextField(blank=True, null=True, unique=True)),
                ('phone', models.TextField(blank=True, null=True, unique=True)),
                ('avatar', models.TextField(blank=True, default='', null=True)),
                ('password', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('content', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('blog_category', models.ForeignKey(db_column='blogCategoryId', on_delete=django.db.models.deletion.RESTRICT, related_name='blogs', to='store_core.blogcategory')),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='BlogSteps',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('blog', models.ForeignKey(db_column='blogId', on_delete=django.db.models.deletion.RESTRICT, related_name='blogSteps', to='store_core.blog')),
            ],
            options={
                'db_table': 'BlogSteps',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('is_available', models.BooleanField(db_column='isAvailable', default=True)),
                ('is_new', models.BooleanField(db_column='isNew', default=False)),
                ('is_hit', models.BooleanField(db_column='isHit', default=False)),
                ('is_bt', models.BooleanField(db_column='isBt', default=False)),
                ('article', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.TextField(unique=True)),
                ('type', models.TextField(blank=True, null=True)),
                ('product_class', models.TextField(blank=True, db_column='class', null=True)),
                ('line', models.TextField(blank=True, null=True)),
                ('series', models.TextField(blank=True, null=True)),
                ('system', models.TextField(blank=True, null=True)),
                ('version', models.TextField(blank=True, null=True)),
                ('diagonal', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('screen_type', models.TextField(blank=True, db_column='screenType', null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('refresh_rate', models.TextField(blank=True, db_column='refreshRate', null=True)),
                ('density', models.TextField(blank=True, null=True)),
                ('brightness', models.TextField(blank=True, null=True)),
                ('glass', models.TextField(blank=True, null=True)),
                ('aod', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('brand', models.ForeignKey(db_column='brandId', on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='store_core.brand')),
                ('category', models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='store_core.category')),
                ('condition', models.ForeignKey(blank=True, db_column='conditionId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store_core.condition')),
                ('product_model', models.ForeignKey(blank=True, db_column='modelId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store_core.productmodel')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('old_price', models.FloatField(blank=True, db_column='oldPrice', null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('is_available', models.BooleanField(db_column='isAvailable', default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('images', models.JSONField(blank=True, null=True)),
                ('diagonal', models.TextField(blank=True, null=True)),
                ('size', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('color', models.ForeignKey(db_column='colorId', on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='store_core.color')),
                ('memory', models.ForeignKey(db_column='memoryId', on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='store_core.memory')),
                ('product', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='store_core.product')),
                ('sim_type', models.ForeignKey(blank=True, db_column='simTypeId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants_single', to='store_core.simtype')),
            ],
            options={
                'db_table': 'ProductVariant',
            },
        ),
        migrations.CreateModel(
            name='ServiceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('service_brand', models.ForeignKey(blank=True, db_column='serviceBrandId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='store_core.servicebrand')),
            ],
            options={
                'db_table': 'ServiceModel',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('slug', models.TextField(unique=True)),
                ('labor_only', models.IntegerField(db_column='laborOnly')),
                ('labor_with_part', models.IntegerField(db_column='laborWithPart')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('service_model', models.ForeignKey(blank=True, db_column='serviceModelId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='store_core.servicemodel')),
            ],
            options={
                'db_table': 'Service',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantSimType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, null=True)),
                ('product_variant', models.ForeignKey(db_column='productVariantId', on_delete=django.db.models.deletion.CASCADE, related_name='sim_type_links', to='store_core.productvariant')),
                ('sim_type', models.ForeignKey(db_column='simTypeId', on_delete=django.db.models.deletion.RESTRICT, related_name='variant_links', to='store_core.simtype')),
            ],
            options={
                'db_table': 'ProductVariantSimType',
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('products', models.JSONField()),
                ('total_sum', models.IntegerField(db_column='totalSum')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('user', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store_core.storeuser')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
