# Generated by Django 5.0.7 on 2026-05-27 12:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ('-created_at',), 'verbose_name': 'Баннер', 'verbose_name_plural': 'Баннеры'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',), 'verbose_name': 'Статья блога', 'verbose_name_plural': 'Статьи блога'},
        ),
        migrations.AlterModelOptions(
            name='blogcategory',
            options={'ordering': ('name',), 'verbose_name': 'Категория блога', 'verbose_name_plural': 'Категории блога'},
        ),
        migrations.AlterModelOptions(
            name='blogsteps',
            options={'ordering': ('blog', 'created_at'), 'verbose_name': 'Шаг статьи', 'verbose_name_plural': 'Шаги статей'},
        ),
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ('name',), 'verbose_name': 'Бренд', 'verbose_name_plural': 'Бренды'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Категория каталога', 'verbose_name_plural': 'Категории каталога'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'ordering': ('name',), 'verbose_name': 'Цвет', 'verbose_name_plural': 'Цвета'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'ordering': ('name',), 'verbose_name': 'Состояние товара', 'verbose_name_plural': 'Состояния товаров'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('name',), 'verbose_name': 'Информационный блок', 'verbose_name_plural': 'Информационные блоки'},
        ),
        migrations.AlterModelOptions(
            name='memory',
            options={'ordering': ('name',), 'verbose_name': 'Объём памяти', 'verbose_name_plural': 'Объёмы памяти'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-created_at',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='productmodel',
            options={'ordering': ('name',), 'verbose_name': 'Модель устройства', 'verbose_name_plural': 'Модели устройств'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('product', 'price'), 'verbose_name': 'Вариант товара', 'verbose_name_plural': 'Варианты товаров'},
        ),
        migrations.AlterModelOptions(
            name='productvariantsimtype',
            options={'ordering': ('product_variant',), 'verbose_name': 'Цена SIM для варианта', 'verbose_name_plural': 'Цены SIM для вариантов'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('service_model', 'name'), 'verbose_name': 'Услуга ремонта', 'verbose_name_plural': 'Услуги ремонта'},
        ),
        migrations.AlterModelOptions(
            name='servicebrand',
            options={'ordering': ('name',), 'verbose_name': 'Бренд сервиса (ремонт)', 'verbose_name_plural': 'Бренды сервиса'},
        ),
        migrations.AlterModelOptions(
            name='servicemodel',
            options={'ordering': ('service_brand', 'name'), 'verbose_name': 'Модель сервиса', 'verbose_name_plural': 'Модели сервиса'},
        ),
        migrations.AlterModelOptions(
            name='simtype',
            options={'ordering': ('name',), 'verbose_name': 'Тип SIM', 'verbose_name_plural': 'Типы SIM'},
        ),
        migrations.AlterModelOptions(
            name='storeadmin',
            options={'ordering': ('username',), 'verbose_name': 'Администратор', 'verbose_name_plural': 'Администраторы'},
        ),
        migrations.AlterModelOptions(
            name='storeorder',
            options={'ordering': ('-created_at',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='storeuser',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='reatedAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img_mobile',
            field=models.TextField(db_column='imgMobile', verbose_name='Изображение (мобильный)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img_pc',
            field=models.TextField(db_column='imgPc', verbose_name='Изображение (ПК)'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_category',
            field=models.ForeignKey(db_column='blogCategoryId', on_delete=django.db.models.deletion.RESTRICT, related_name='blogs', to='store_core.blogcategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.TextField(verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='blogsteps',
            name='blog',
            field=models.ForeignKey(db_column='blogId', on_delete=django.db.models.deletion.RESTRICT, related_name='blogSteps', to='store_core.blog', verbose_name='Статья'),
        ),
        migrations.AlterField(
            model_name='blogsteps',
            name='content',
            field=models.TextField(verbose_name='Содержимое'),
        ),
        migrations.AlterField(
            model_name='blogsteps',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='blogsteps',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='blogsteps',
            name='title',
            field=models.TextField(verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='blogsteps',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.TextField(blank=True, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='color',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='color',
            name='hex',
            field=models.TextField(blank=True, null=True, verbose_name='HEX-код'),
        ),
        migrations.AlterField(
            model_name='color',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='color',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='condition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='info',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='info',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='memory',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='aod',
            field=models.TextField(blank=True, null=True, verbose_name='Always On Display'),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.TextField(blank=True, null=True, verbose_name='Артикул'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(db_column='brandId', on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='store_core.brand', verbose_name='Бренд'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brightness',
            field=models.TextField(blank=True, null=True, verbose_name='Яркость'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='categoryId', on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='store_core.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.ForeignKey(blank=True, db_column='conditionId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store_core.condition', verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='product',
            name='density',
            field=models.TextField(blank=True, null=True, verbose_name='Плотность пикселей'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='diagonal',
            field=models.TextField(blank=True, null=True, verbose_name='Диагональ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='glass',
            field=models.TextField(blank=True, null=True, verbose_name='Стекло'),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(db_column='isAvailable', default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bt',
            field=models.BooleanField(db_column='isBt', default=False, verbose_name='Bluetooth'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_hit',
            field=models.BooleanField(db_column='isHit', default=False, verbose_name='Хит'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new',
            field=models.BooleanField(db_column='isNew', default=False, verbose_name='Новинка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='line',
            field=models.TextField(blank=True, null=True, verbose_name='Линейка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_class',
            field=models.TextField(blank=True, db_column='class', null=True, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.ForeignKey(blank=True, db_column='modelId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='store_core.productmodel', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='refresh_rate',
            field=models.TextField(blank=True, db_column='refreshRate', null=True, verbose_name='Частота обновления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.TextField(blank=True, null=True, verbose_name='Разрешение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen_type',
            field=models.TextField(blank=True, db_column='screenType', null=True, verbose_name='Тип экрана'),
        ),
        migrations.AlterField(
            model_name='product',
            name='series',
            field=models.TextField(blank=True, null=True, verbose_name='Серия'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.TextField(blank=True, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.TextField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='product',
            name='system',
            field=models.TextField(blank=True, null=True, verbose_name='Система'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.TextField(blank=True, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='product',
            name='version',
            field=models.TextField(blank=True, null=True, verbose_name='Версия'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=models.ForeignKey(db_column='colorId', on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='store_core.color', verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='diagonal',
            field=models.TextField(blank=True, null=True, verbose_name='Диагональ'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='discount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Скидка, %'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='images',
            field=models.JSONField(blank=True, null=True, verbose_name='Изображения (JSON)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='is_available',
            field=models.BooleanField(db_column='isAvailable', default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='memory',
            field=models.ForeignKey(db_column='memoryId', on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='store_core.memory', verbose_name='Память'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='old_price',
            field=models.FloatField(blank=True, db_column='oldPrice', null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='store_core.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sim_type',
            field=models.ForeignKey(blank=True, db_column='simTypeId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants_single', to='store_core.simtype', verbose_name='Тип SIM (основной)'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=models.TextField(blank=True, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='productvariantsimtype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='productvariantsimtype',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Цена за тип SIM'),
        ),
        migrations.AlterField(
            model_name='productvariantsimtype',
            name='product_variant',
            field=models.ForeignKey(db_column='productVariantId', on_delete=django.db.models.deletion.CASCADE, related_name='sim_type_links', to='store_core.productvariant', verbose_name='Вариант товара'),
        ),
        migrations.AlterField(
            model_name='productvariantsimtype',
            name='sim_type',
            field=models.ForeignKey(db_column='simTypeId', on_delete=django.db.models.deletion.RESTRICT, related_name='variant_links', to='store_core.simtype', verbose_name='Тип SIM'),
        ),
        migrations.AlterField(
            model_name='service',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='service',
            name='labor_only',
            field=models.IntegerField(db_column='laborOnly', verbose_name='Только работа'),
        ),
        migrations.AlterField(
            model_name='service',
            name='labor_with_part',
            field=models.IntegerField(db_column='laborWithPart', verbose_name='Работа с запчастью'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_model',
            field=models.ForeignKey(blank=True, db_column='serviceModelId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='store_core.servicemodel', verbose_name='Модель сервиса'),
        ),
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.TextField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='servicebrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='servicebrand',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='servicebrand',
            name='image',
            field=models.TextField(verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='servicebrand',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='servicebrand',
            name='slug',
            field=models.TextField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='servicebrand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создана'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='name',
            field=models.TextField(verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='service_brand',
            field=models.ForeignKey(blank=True, db_column='serviceBrandId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='store_core.servicebrand', verbose_name='Бренд сервиса'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='slug',
            field=models.TextField(unique=True, verbose_name='Слаг'),
        ),
        migrations.AlterField(
            model_name='servicemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлена'),
        ),
        migrations.AlterField(
            model_name='simtype',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='simtype',
            name='name',
            field=models.TextField(unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='storeadmin',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='storeadmin',
            name='password',
            field=models.TextField(verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='storeadmin',
            name='username',
            field=models.TextField(verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='products',
            field=models.JSONField(verbose_name='Товары (JSON)'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='total_sum',
            field=models.IntegerField(db_column='totalSum', verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлён'),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='user',
            field=models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='store_core.storeuser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='avatar',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='email',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Электронная почта'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='first_name',
            field=models.TextField(blank=True, db_column='firstName', null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='last_name',
            field=models.TextField(blank=True, db_column='lastName', null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='middle_name',
            field=models.TextField(blank=True, db_column='middleName', null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='password',
            field=models.TextField(verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='phone',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_column='updatedAt', verbose_name='Обновлён'),
        ),
    ]
