# Generated by Django 6.0.5 on 2026-05-30 07:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_core', '0003_sync_unmanaged_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('name',), 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ('product', 'price'), 'verbose_name': 'Цена варианта', 'verbose_name_plural': 'Управление ценами'},
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Идентификатор')),
                ('path', models.TextField(blank=True, default='', verbose_name='Путь к файлу')),
                ('alt', models.TextField(blank=True, default='', verbose_name='Alt текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('product', models.ForeignKey(db_column='productId', on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='store_core.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Изображение товара',
                'verbose_name_plural': 'Изображения товаров',
                'db_table': 'ProductImage',
                'ordering': ('sort_order', '-created_at'),
                'managed': True,
            },
        ),
    ]
