# Generated by Django 6.0.5 on 2026-06-04 01:18

import apps.common.file_storage
from django.db import migrations, models


def normalize_image_paths(apps, schema_editor):
    from apps.common.file_storage import normalize_stored_image_path

    def _normalize_model(model, fields):
        for obj in model.objects.all():
            updates = {}
            for field in fields:
                value = getattr(obj, field)
                if not value:
                    continue
                normalized = normalize_stored_image_path(str(value))
                if normalized and normalized != value:
                    updates[field] = normalized
            if updates:
                model.objects.filter(pk=obj.pk).update(**updates)

    _normalize_model(apps.get_model('store_core', 'Banner'), ('img_pc', 'img_mobile'))
    _normalize_model(apps.get_model('store_core', 'Blog'), ('image',))
    _normalize_model(apps.get_model('store_core', 'Category'), ('icon',))
    _normalize_model(apps.get_model('store_core', 'ServiceBrand'), ('image',))
    _normalize_model(apps.get_model('store_core', 'StoreUser'), ('avatar',))
    _normalize_model(apps.get_model('store_core', 'ProductImage'), ('path',))


class Migration(migrations.Migration):

    dependencies = [
        ('store_core', '0006_storeorder_contact_fields'),
    ]

    operations = [
        migrations.RunPython(normalize_image_paths, migrations.RunPython.noop),
        migrations.RenameField(
            model_name='productimage',
            old_name='path',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(
                blank=True,
                max_length=512,
                upload_to=apps.common.file_storage.image_upload_to,
                verbose_name='Изображение',
            ),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_column='createdAt', verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img_mobile',
            field=models.ImageField(
                db_column='imgMobile',
                max_length=512,
                upload_to=apps.common.file_storage.image_upload_to,
                verbose_name='Изображение (мобильный)',
            ),
        ),
        migrations.AlterField(
            model_name='banner',
            name='img_pc',
            field=models.ImageField(
                db_column='imgPc',
                max_length=512,
                upload_to=apps.common.file_storage.image_upload_to,
                verbose_name='Изображение (ПК)',
            ),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=apps.common.file_storage.image_upload_to,
                verbose_name='Изображение',
            ),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=apps.common.file_storage.image_upload_to,
                verbose_name='Иконка',
            ),
        ),
        migrations.AlterField(
            model_name='servicebrand',
            name='image',
            field=models.ImageField(
                max_length=512,
                upload_to=apps.common.file_storage.image_upload_to,
                verbose_name='Изображение',
            ),
        ),
        migrations.AlterField(
            model_name='storeuser',
            name='avatar',
            field=models.ImageField(
                blank=True,
                max_length=512,
                null=True,
                upload_to=apps.common.file_storage.image_upload_to,
                verbose_name='Аватар',
            ),
        ),
    ]
