# Generated by Django 6.0.5 on 2026-06-12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_core', '0008_brand_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(
                blank=True,
                db_column='colorId',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='product_images',
                to='store_core.color',
                verbose_name='Цвет',
                help_text='Привязка к цвету: на сайте фото меняются при выборе цвета.',
            ),
        ),
    ]
