from django.urls import path

from apps.catalog.views_dict import (
    BrandDetailView,
    BrandListCreateView,
    CategoryDetailView,
    CategoryListCreateView,
    CategorySetSlugView,
    ColorDetailView,
    ColorListCreateView,
    ConditionDetailView,
    ConditionListCreateView,
    MemoryDetailView,
    MemoryListCreateView,
    ProductModelDetailView,
    ProductModelListCreateView,
    SimTypeDetailView,
    SimTypeListCreateView,
)
from apps.catalog.views_filtr import (
    FiltrBestOffersView,
    FiltrBySimtypeView,
    FiltrCleanSimView,
    FiltrFilterDataView,
    FiltrIsHasProductView,
    FiltrPostView,
    FiltrBrandsModelsView,
)
from apps.catalog.views_product import (
    ProductByCategoryIdView,
    ProductByCategorySlugView,
    ProductCreateView,
    ProductDetailView,
    ProductHelpView,
    ProductListPagedView,
    ProductRepairView,
    ProductSearchView,
    ProductSlugDetailView,
    ProductTradeInView,
    ProductVariantDeleteView,
    ProductVariantImageDeleteView,
    ProductVariantPatchView,
)

urlpatterns = [
    path('filtr', FiltrPostView.as_view()),
    path('filtr/filter-data/<slug:slug>', FiltrFilterDataView.as_view()),
    path('filtr/brands-and-models-by-category/<int:category_id>', FiltrBrandsModelsView.as_view()),
    path('filtr/best-offers', FiltrBestOffersView.as_view()),
    path('filtr/is-has-product/<slug:slug>', FiltrIsHasProductView.as_view()),
    path('filtr/clean-all-sim-type-id-products', FiltrCleanSimView.as_view()),
    path('filtr/filtr-by-varianst-sim-type-products/<str:simtype_id>', FiltrBySimtypeView.as_view()),
    path('product/help', ProductHelpView.as_view()),
    path('product/trade-in-request', ProductTradeInView.as_view()),
    path('product/repair-request', ProductRepairView.as_view()),
    path('product/search/<str:query>', ProductSearchView.as_view()),
    path('product/all/<int:page>/<int:limit>', ProductListPagedView.as_view()),
    path('product/category/slug/<slug:slug>/<int:page>/<int:limit>', ProductByCategorySlugView.as_view()),
    path('product/category/<int:category_id>/<int:page>/<int:limit>', ProductByCategoryIdView.as_view()),
    path('product/slug/<slug:slug>', ProductSlugDetailView.as_view()),
    path('product/variant/remove/<str:variant_id>', ProductVariantDeleteView.as_view()),
    path('product/variant/<str:variant_id>/images/<str:image_id>', ProductVariantImageDeleteView.as_view()),
    path('product/variant/<str:variant_id>', ProductVariantPatchView.as_view()),
    path('product/<int:pk>', ProductDetailView.as_view()),
    path('product', ProductCreateView.as_view()),
    path('color', ColorListCreateView.as_view()),
    path('color/<int:pk>', ColorDetailView.as_view()),
    path('memory', MemoryListCreateView.as_view()),
    path('memory/<int:pk>', MemoryDetailView.as_view()),
    path('brand', BrandListCreateView.as_view()),
    path('brand/<int:pk>', BrandDetailView.as_view()),
    path('category', CategoryListCreateView.as_view()),
    path('category/set-slug', CategorySetSlugView.as_view()),
    path('category/<int:pk>', CategoryDetailView.as_view()),
    path('condition', ConditionListCreateView.as_view()),
    path('condition/<str:pk>', ConditionDetailView.as_view()),
    path('simtype', SimTypeListCreateView.as_view()),
    path('simtype/<str:pk>', SimTypeDetailView.as_view()),
    path('product-model', ProductModelListCreateView.as_view()),
    path('product-model/<int:pk>', ProductModelDetailView.as_view()),
]
