# Generated by Django 5.0.7 on 2026-05-27 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='Пользователь')),
                ('variant_id', models.UUIDField(db_index=True, verbose_name='Вариант товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Позиция корзины',
                'verbose_name_plural': 'Корзина',
                'db_table': 'store_cart_item',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, verbose_name='Пользователь')),
                ('variant_id', models.UUIDField(db_index=True, verbose_name='Вариант товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
                'db_table': 'store_favorite',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(max_length=255, verbose_name='Автор')),
                ('text', models.TextField(blank=True, default='', verbose_name='Текст')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Оценка')),
                ('source', models.CharField(choices=[('avito', 'Avito'), ('yandex', 'Yandex Maps'), ('site', 'Сайт')], default='site', max_length=32, verbose_name='Источник')),
                ('video_url', models.URLField(blank=True, default='', verbose_name='Видео URL')),
                ('thumbnail', models.TextField(blank=True, default='', verbose_name='Превью')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'store_review',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(default='+7 (966) 861-52-42', max_length=64, verbose_name='Телефон')),
                ('email', models.EmailField(default='info@geniusstore.ru', max_length=254, verbose_name='Email')),
                ('address', models.TextField(default='Санкт-Петербург, Невский проспект 112-114', verbose_name='Адрес')),
                ('telegram_url', models.URLField(blank=True, default='', verbose_name='Telegram')),
                ('vk_url', models.URLField(blank=True, default='', verbose_name='VK')),
                ('whatsapp_url', models.URLField(blank=True, default='', verbose_name='WhatsApp')),
                ('map_lat', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('map_lng', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('advantages', models.JSONField(blank=True, default=list, verbose_name='Преимущества (JSON)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
                'db_table': 'store_site_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('user_id', 'variant_id'), name='uniq_cart_user_variant'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user_id', 'variant_id'), name='uniq_favorite_user_variant'),
        ),
    ]
